package com.snapwiz.selenium.tests.staf.learningspaces.pagefactory.Assignments;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import java.util.List;

/**
 * Created by durgapathi on 4/11/15.
 */
public class CopyAllAssignments {

    @FindBy(className = "ls-ins-copy-assignments-dialogBox")
    public WebElement assignmentDialogBox;

    @FindBy(className = "ls-ins-copy-assignments-dialogBox")
    public List<WebElement> assignmentDialogBoxDisplay;

    @FindBy(xpath = ".//div[@class='ls-class-section-filter-block ls-source-class-sections scrollbar-wrapper']/div")
    public WebElement sourceClassSection;

    @FindBy(xpath = ".//div[@class='ls-class-section-filter-block ls-destination-class-sections scrollbar-wrapper']/div")
    public WebElement destinationClassSection;

    @FindBy(xpath = ".//div[@class='ls-class-section-filter-block ls-source-class-sections scrollbar-wrapper']/div/a")
    public List<WebElement> sourceClassSectionDropDown;

    @FindBy(xpath = ".//div[@class='ls-class-section-filter-block ls-destination-class-sections scrollbar-wrapper']/div/a")
    public List<WebElement> destinationClassSectionDropDown;

    @FindBy(xpath = ".//*[@class='ls-source-class-section-block']//li/a")
    public List<WebElement> getSourceClassSectionNames;

    @FindBy(xpath = ".//*[@class='ls-destination-class-section-block']//li/a")
    public List<WebElement> getDestinationClassSectionNames;

    @FindBy(className = "ins-dialogBox-next")
    public WebElement nextButtonInStep1;

    @FindBy(className = "ls-copy-error-msg")
    public WebElement errorMessageInStep1;

    @FindBy(className = "ins-dialogClose")
    public WebElement closePopup;

    @FindBy(className = "ins-dialogBox-Cancel")
    public WebElement cancelLink;

    @FindBy(className = "ls-copy-step2-header")
    public WebElement step2Header;

    @FindBy(className = "ls-copy-step1-header")
    public WebElement step1Header;

    @FindBy(xpath = ".//div[@class='dateImg ls-copy-assignment-accessible-date']/input")
    public List<WebElement> sourceAccessibleDate;

    @FindBy(className = "ui-state-default")
    public List<WebElement> date;

    @FindBy(css = "a[data-handler='next']")
    public WebElement clickNextMonth;

    @FindBy(className = "ins-dialogBox-assign")
    public WebElement assignAssignments;

    @FindBy(className = "ins-dialogHeader-title")
    public WebElement dialogHeader;

    @FindBy(className = "ls-dialogBox-navigate-back")
    public WebElement backButtonInStept2;

    @FindBy(css = "span[class='ls-copy-source-name ellipsis']")
    public WebElement sourceCSNameInSteps2;

    @FindBy(css = "span[class='ls-copy-destination-name ellipsis']")
    public WebElement destinationCSNameInSteps2;

    @FindBy(className = "additional-desc-help-icon")
    public WebElement additionalHelpIcon;

    @FindBy(className = "ls-copy-assignment-row")
    public List<WebElement> assignmentCard;

    @FindBy(css = "div[class='notification-text-span notification-message-text-span']")
    public List<WebElement> notificationInStep2;

    @FindBy(css = "div[class='notification-close-btn-section notification-message-link']")
    public List<WebElement> notificationClose;

    @FindBy(css = "div[class='notification-message-yes-section notification-message-link']")
    public List<WebElement> notificationYes;

    @FindBy(css = "div[class='notification-message-no-section notification-message-link']")
    public List<WebElement> notificationNo;

    @FindBy(css = "label[class='ls-auto-generate-check checked']")
    public WebElement autoGenerateDatesChecked;

    @FindBy(css = "label[class='ls-auto-generate-check']")
    public WebElement autoGenerateDatesUnChecked;

}
